In [3]:
 # Necessary libraries
import pandas as pd
import numpy  as np
import csv 
from scipy import stats

In [4]:
# Reading in the dataset
df = pd.read_csv('03-Oct-2023_patAnalysis_2.csv')

# Remove NaN values of PAT
df_squashed = df.dropna(subset=['wrist@(9mm,809nm)_filtered_pat_bottomTI'])
#Remove rows of NaN values of blood pressure
df_squashed = df_squashed.dropna(subset = ["blood pressure_systolic"])
df_squashed

# Identify outliers of column by computing z-score
z = np.abs(stats.zscore(df_squashed['wrist@(9mm,809nm)_filtered_pat_bottomTI']))

# Identify outliers as pat_filtered with a z-score greater than 3
threshold = 3
outliers = df_squashed['wrist@(9mm,809nm)_filtered_pat_bottomTI'][z > threshold]

# Print the outliers
print(outliers)

# Remove outliers
df_squashed = df_squashed.drop(outliers.index)
df_squashed

773     0.697993
1182    2.103295
1186    2.149519
1196    1.582183
1198    1.144425
1544    1.061184
1548    1.133318
1556    1.133318
Name: wrist@(9mm,809nm)_filtered_pat_bottomTI, dtype: float64

,"wrist@(9mm,809nm)_date","wrist@(9mm,809nm)_delay_s","wrist@(9mm,809nm)_raw_pat","wrist@(9mm,809nm)_filtered_pat_bottomTI","wrist@(9mm,809nm)_mask",blood pressure_systolic,blood pressure_mean,blood pressure_diastolic
31,27/10/2022 10:49,29.016,NaN,0.415027,1,73.6288,52.06840,45.20960
44,27/10/2022 10:49,40.335,0.415027,0.372815,1,94.0030,65.08525,52.00100
51,27/10/2022 10:49,46.522,0.329416,0.369593,1,97.9044,67.67830,53.90440
63,27/10/2022 10:49,60.487,0.307726,0.311529,1,100.6974,69.77305,56.69740
74,27/10/2022 10:49,69.969,0.316886,0.310813,1,100.2031,69.60155,56.60155
...,...,...,...,...,...,...,...,...
2321,27/10/2022 11:52,3798.134,0.180315,0.185350,1,116.1598,80.15980,60.96650
2322,27/10/2022 11:52,3799.034,0.181337,0.185817,1,115.8898,79.88980,60.74150
2323,27/10/2022 11:52,3799.944,0.186739,0.186459,1,115.6168,79.61680,60.51400
2324,27/10/2022 11:52,3800.842,0.190720,0.187216,1,115.3474,79.34740,60.28950
2325,27/10/2022 11:52,3801.720,0.193140,0.187933,1,115.0840,79.08400,60.07000