In [20]:
 # Necessary libraries
import pandas as pd
import numpy  as np
import csv 
from scipy import stats

import matplotlib.pyplot as plt

In [47]:
# Reading in the dataset
df = pd.read_csv('03-Oct-2023_patAnalysis_2.csv')
# Drop column of NaN  values of blod pressure
df = df.dropna(subset = ["blood pressure_systolic"])
# Make a copy of the dataframe to fill in  NaN of PAT with mean NaN
df_outlier = df.copy()
df_outlier['wrist@(9mm,809nm)_filtered_pat_bottomTI'] = df_outlier['wrist@(9mm,809nm)_filtered_pat_bottomTI'].fillna(df_outlier['wrist@(9mm,809nm)_filtered_pat_bottomTI'].mean())

# Commpute the z-statistic
z = np.abs(stats.zscore(df_outlier['wrist@(9mm,809nm)_filtered_pat_bottomTI']))
# Identify outliers as the pat_filtered with a z-score greater than 3
threshold = 3
outliers = df_outlier['wrist@(9mm,809nm)_filtered_pat_bottomTI'][z > threshold]
print(outliers)



# Remove outliers
df = df.drop(outliers.index)
df

773     0.697993
1182    2.103295
1186    2.149519
1196    1.582183
1198    1.144425
1544    1.061184
1548    1.133318
1556    1.133318
Name: wrist@(9mm,809nm)_filtered_pat_bottomTI, dtype: float64

,"wrist@(9mm,809nm)_date","wrist@(9mm,809nm)_delay_s","wrist@(9mm,809nm)_raw_pat","wrist@(9mm,809nm)_filtered_pat_bottomTI","wrist@(9mm,809nm)_mask",blood pressure_systolic,blood pressure_mean,blood pressure_diastolic
24,27/10/2022 10:49,22.626,NaN,NaN,0,62.1268,44.71990,41.3756
25,27/10/2022 10:49,23.482,NaN,NaN,0,63.6676,45.70430,41.8892
26,27/10/2022 10:49,24.377,0.539193,NaN,0,65.2786,46.73355,42.4262
27,27/10/2022 10:49,25.307,NaN,NaN,0,66.9526,47.80305,42.9842
28,27/10/2022 10:49,26.263,0.725741,NaN,0,68.6734,48.90245,43.5578
...,...,...,...,...,...,...,...,...
2321,27/10/2022 11:52,3798.134,0.180315,0.185350,1,116.1598,80.15980,60.9665
2322,27/10/2022 11:52,3799.034,0.181337,0.185817,1,115.8898,79.88980,60.7415
2323,27/10/2022 11:52,3799.944,0.186739,0.186459,1,115.6168,79.61680,60.5140
2324,27/10/2022 11:52,3800.842,0.190720,0.187216,1,115.3474,79.34740,60.2895
2325,27/10/2022 11:52,3801.720,0.193140,0.187933,1,115.0840,79.08400,60.0700